#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("BusinessCal.Droid.Resource", IsApplication=true)]

namespace BusinessCal.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040000
			public const int joycesoftware_color = 2130968576;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_action_addtask = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_action_delete = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_action_save = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_checkmark = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_launcher = 2130837508;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080004
			public const int NameLabel = 2131230724;
			
			// aapt resource value: 0x7f080006
			public const int NotesLabel = 2131230726;
			
			// aapt resource value: 0x7f080012
			public const int btnBreakEven = 2131230738;
			
			// aapt resource value: 0x7f08000a
			public const int btnCalculate = 2131230730;
			
			// aapt resource value: 0x7f080011
			public const int btnGrossProfit = 2131230737;
			
			// aapt resource value: 0x7f080014
			public const int btnSalePrice = 2131230740;
			
			// aapt resource value: 0x7f080013
			public const int btnVat = 2131230739;
			
			// aapt resource value: 0x7f080019
			public const int label1 = 2131230745;
			
			// aapt resource value: 0x7f08001b
			public const int label8 = 2131230747;
			
			// aapt resource value: 0x7f080009
			public const int lblBreakEvenPoint = 2131230729;
			
			// aapt resource value: 0x7f080003
			public const int lblDateOfBirth = 2131230723;
			
			// aapt resource value: 0x7f08000d
			public const int lblGrossProfit = 2131230733;
			
			// aapt resource value: 0x7f08000e
			public const int lblGrossProfitMargin = 2131230734;
			
			// aapt resource value: 0x7f080000
			public const int lblSex = 2131230720;
			
			// aapt resource value: 0x7f080002
			public const int lblTagNumber = 2131230722;
			
			// aapt resource value: 0x7f08001d
			public const int lblVAT = 2131230749;
			
			// aapt resource value: 0x7f080001
			public const int linearLayout1 = 2131230721;
			
			// aapt resource value: 0x7f080020
			public const int menu_add_task = 2131230752;
			
			// aapt resource value: 0x7f08001f
			public const int menu_delete_task = 2131230751;
			
			// aapt resource value: 0x7f08001e
			public const int menu_save_task = 2131230750;
			
			// aapt resource value: 0x7f080022
			public const int mnuLogout = 2131230754;
			
			// aapt resource value: 0x7f080021
			public const int mnuMyDetails = 2131230753;
			
			// aapt resource value: 0x7f08000f
			public const int tableLayout1 = 2131230735;
			
			// aapt resource value: 0x7f080010
			public const int tableRow1 = 2131230736;
			
			// aapt resource value: 0x7f08000c
			public const int txtCostOfGoods = 2131230732;
			
			// aapt resource value: 0x7f080015
			public const int txtCostPrice = 2131230741;
			
			// aapt resource value: 0x7f080005
			public const int txtFixedExpenses = 2131230725;
			
			// aapt resource value: 0x7f080017
			public const int txtMargin = 2131230743;
			
			// aapt resource value: 0x7f08001a
			public const int txtPrice = 2131230746;
			
			// aapt resource value: 0x7f08001c
			public const int txtPriceIncVat = 2131230748;
			
			// aapt resource value: 0x7f08000b
			public const int txtSales = 2131230731;
			
			// aapt resource value: 0x7f080018
			public const int txtSalesPrice = 2131230744;
			
			// aapt resource value: 0x7f080008
			public const int txtTotalSales = 2131230728;
			
			// aapt resource value: 0x7f080016
			public const int txtValueAddedTax = 2131230742;
			
			// aapt resource value: 0x7f080007
			public const int txtVariableExpenses = 2131230727;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AnimalListItem = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int scrBreakEven = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int scrGrossProfit = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int scrHomeScreen = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int scrSalesPrice = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int scrVAT = 2130903045;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f070000
			public const int menu_detailsscreen = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int menu_homescreen = 2131165185;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050006
			public const int BreakEvenPoint = 2131034118;
			
			// aapt resource value: 0x7f050002
			public const int Calculate = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int MarginCalculation = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int PriceCalculation = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int VAT = 2131034117;
			
			// aapt resource value: 0x7f050001
			public const int app_name = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int Theme_FlyingCow = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
